### ISSUE TITLE
Error when importing pyoo on alpine 3.9

### ISSUE THREAD

**Issue by dmarkey** [seznam/pyoo#22]
`
>>> import sys
>>> sys.path.append('/usr/lib/libreoffice/program')
>>> import pyoo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pyoo.py", line 29, in <module>
    FORMAT_TEXT = uno.getConstantByName('com.sun.star.i18n.NumberFormatIndex.TEXT')
  File "/usr/lib/libreoffice/program/uno.py", line 72, in getConstantByName
    return pyuno.getConstantByName(constant)
uno.RuntimeException: com.sun.star.i18n.NumberFormatIndex.TEXT
`
:(

**Comment by Meiji01** [comment]
same error encountered. Anyone can help please
